services:
  go_web_app:
    build:  
      context: .
      dockerfile: Dockerfile.prod
    container_name: go_web_app
    env_file: 
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    expose:
      - "3000"
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - go_web_app
