services:
  go_web_app:
    build: .
    container_name: go_web_app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app # Sincroniza tu carpeta actual con /app en el contenedor
    command: air -c .air.toml # Asegúrate de apuntar a tu configuración de air
    env_file: [.env]
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
