-- 1. Limpiar la tabla de forma segura sin romper la estructura de Supabase
TRUNCATE TABLE "public"."nomenclatura" RESTART IDENTITY CASCADE;

-- 2. Insertar el catálogo de cuentas unificado y depurado
INSERT INTO
  "public"."nomenclatura" ("codigo", "nombre", "saldo", "categoria", "es_costo", "es_efectivo", "es_variable")
VALUES
  -- Balance general 100000, Activo 110000, Corriente 111000 
  -- Activo Disponible 111100
  (111101, 'Caja', 'activo', 'Disponible', FALSE, TRUE, FALSE),
  (111102, 'Bancos', 'activo', 'Disponible', FALSE, TRUE, FALSE),
  (111103, 'Caja y Bancos', 'activo', 'Disponible', FALSE, TRUE, FALSE),
  (111104, 'Caja Chica', 'activo', 'Disponible', FALSE, TRUE, FALSE),
  (111105, 'Fondo Fijo', 'activo', 'Disponible', FALSE, TRUE, FALSE),
  (111106, 'Caja Chica de Fábrica', 'activo', 'Disponible', TRUE, TRUE, FALSE),
  (111107, 'Divisas Adquiridas', 'activo', 'Disponible', FALSE, TRUE, FALSE),
  (111108, 'Especies Fiscales', 'activo', 'Disponible', FALSE, TRUE, FALSE),

  -- Activo Exigible 111200
  (111201, 'Deudores no Comerciales', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111202, 'Documentos por Cobrar', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111203, 'Clientes', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111204, '(-)Reserva para Cuentas Incobrables', 'pasivo', 'Exigible', FALSE, TRUE, FALSE),
  (111205, '(-)Provisión para Cuentas Incobrables', 'pasivo', 'Exigible', FALSE, FALSE, FALSE),
  (111206, '(-)Provisión para Cuentas Malas', 'pasivo', 'Exigible', FALSE, FALSE, FALSE),
  (111207, '(-)Provisión para Cuentas de Difícil Cobro', 'pasivo', 'Exigible', FALSE, FALSE, FALSE),
  (111208, '(-)Provisión para Cuentas Morosas', 'pasivo', 'Exigible', FALSE, FALSE, FALSE),
  (111209, '(-)Reserva para Cuentas Malas', 'pasivo', 'Exigible', FALSE, FALSE, FALSE),
  (111210, '(-)Reserva para Cuentas Morosas', 'pasivo', 'Exigible', FALSE, FALSE, FALSE),
  (111211, '(-)Reserva para Cuentas de Difícil Cobro', 'pasivo', 'Exigible', FALSE, FALSE, FALSE),
  (111212, '(-)Estimación para Cuentas Incobrables', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (111213, '(-)Estimación para Cuentas Malas', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (111214, '(-)Estimación para Cuentas Dudosas', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (111215, '(-)Estimación para Cuentas de Difícil Cobro', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (111216, 'Anticipo sobre Compras', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111217, 'Crédito Fiscal', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111218, 'Documentos por Cobrar a Corto Plazo', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111219, 'ISR Retenido por Acreditar Sobre Ventas', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111220, '(-) Documentos Descontados', 'pasivo', 'Exigible', FALSE, TRUE, FALSE),
  (111221, 'Productos por Cobrar', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111222, 'Propaganda Pagada por Anticipado', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111223, 'Publicidad Pagada por Anticipado', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111224, 'Seguros Anticipados', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111225, 'Seguros Pagados por Anticipado', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111226, 'Seguros no Vencidos', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111227, 'Sueldos Pagados por Anticipado', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111228, 'Valores Mobiliarios', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111229, 'Valores Mobiliarios a Corto Plazo', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111230, 'IVA por Cobrar', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111231, 'IVA (deudor)', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111233, 'Portafolio de Inversiones a Corto Plazo', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111234, 'Primas de Seguro no Vencidas', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111235, 'Impuesto sobre la Renta Pag. por Anticipado', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111236, 'ISO por Acreditar', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111237, 'ISR Retenido S/Ventas por Acreditar', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111238, 'Intereses por Cobrar', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111239, 'Intereses Pagados por Anticipado', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111240, 'Inversiones', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111241, 'Inversiones a Corto Plazo', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111242, 'Inversiones en Bonos a Corto Plazo', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111243, 'Inversiones Financieras a Corto Plazo', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111244, 'Inversiones a Largo Plazo', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111245, 'Inversiones en Valores', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111246, 'Inversiones en Valores a Corto Plazo', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111247, 'Deudores Diversos', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111248, 'Deudores Empleados', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111249, 'Deudores Varios', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111250, 'Dividendos por Cobrar', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111251, 'Documentos por Cobrar a corto plazo', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111252, 'Efectos por Cobrar', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111253, 'Corresponsales (deudor)', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111254, 'Cuenta Promesa', 'activo', 'Exigible', FALSE, FALSE, FALSE),
  (111255, 'Anticipo de Clientes', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111256, 'Anticipo a Proveedores', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111257, 'Acciones Adquiridas', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111258, 'Valores de Inmediata Realización', 'activo', 'Exigible', FALSE, TRUE, FALSE),
  (111259, 'Documentos por Cobrar a Largo Plazo', 'activo', 'Exigible', FALSE, FALSE, FALSE),

  -- Activo Realizable 111300
  (111301, 'Mercaderias', 'activo', 'Realisable', FALSE, TRUE, FALSE),
  (111302, 'Papelería y útiles', 'activo', 'Realisable', FALSE, TRUE, FALSE),
  (111303, 'Materia Prima', 'activo', 'Realisable', TRUE, TRUE, TRUE),
  (111304, 'Productos en Proceso', 'activo', 'Realisable', TRUE, TRUE, FALSE),
  (111305, 'Productos Terminados', 'activo', 'Realisable', TRUE, TRUE, FALSE),
  (111306, 'Papelería y Útiles (existencia)', 'activo', 'Realisable', FALSE, FALSE, FALSE),
  (111307, 'Mercaderías Enviadas en Consignación', 'activo', 'Realisable', FALSE, FALSE, FALSE),
  (111308, 'Material de Empaque', 'activo', 'Realisable', FALSE, TRUE, TRUE),

  -- Activo No corriente 112000 (Financiero a Largo Plazo)
  (112001, 'Valores Mobiliarios a Largo Plazo', 'activo', 'ActivoNoCorr', FALSE, TRUE, FALSE),
  (112002, 'Portafolio de Inversiones a Largo Plazo', 'activo', 'ActivoNoCorr', FALSE, TRUE, FALSE),
  (112003, 'Inversiones en Bonos a Largo Plazo', 'activo', 'ActivoNoCorr', FALSE, TRUE, FALSE),
  (112004, 'Inversiones Financieras a Largo Plazo', 'activo', 'ActivoNoCorr', FALSE, TRUE, FALSE),
  (112005, 'Inversiones a Largo Plazo', 'activo', 'ActivoNoCorr', FALSE, TRUE, FALSE),
  (112006, 'Inversiones en Valores a Largo Plazo', 'activo', 'ActivoNoCorr', FALSE, TRUE, FALSE),
  (112007, 'Documentos por Cobrar a Largo Plazo', 'activo', 'ActivoNoCorr', FALSE, FALSE, FALSE),
  (112008, 'Depósitos en Garantía', 'activo', 'ActivoNoCorr', FALSE, TRUE, FALSE),

  -- Activo No corriente Propiedad, Planta y Equipo 112100 (Reguladoras con saldo 'pasivo')
  (112101, 'Mobiliario y Equipo', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112102, '(-) Deprec. Acu. Mobiliario y Equipo', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112103, 'Equipo de Computo', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112104, '(-) Deprec. Acu. de Equipo de Computacón', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112105, 'Sistemas Informáticos o Eq. de Comput.', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112106, '(-) Deprec. Acu. Sistemas Informáticos o Eq. de Comput.', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112107, 'Edificios', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112108, '(-) Deprec. Acu. Edificios', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112109, 'Vehículos', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112110, '(-) Deprec. Acu. Vehículos', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112111, 'Terrenos', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112112, 'Vehículos de Reparto', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112113, '(-) Deprec. Acu. Vehículos de Reparto', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112114, 'Maquinaria', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112115, '(-) Deprec. Acu. Maquinaria', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112116, 'Herramientas', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112117, '(-) Deprec. Acu. Herramientas', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112118, 'Edificios de Fábrica', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112119, '(-) Deprec. Acu. Edificios de Fábrica', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112120, 'Cristalería y Peltre', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112121, '(-) Deprec. Acu. Cristalería y Peltre', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112122, 'Útiles y Enseres', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112123, '(-) Deprec. Acu. Útiles y Enseres', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112124, 'Inmuebles', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),
  (112125, '(-) Deprec. Acu. Inmuebles', 'pasivo', 'PropPlanEqui', FALSE, FALSE, FALSE),
  (112126, 'Terrenos de Expansión', 'activo', 'PropPlanEqui', FALSE, TRUE, FALSE),

  -- Activo Gastos Intangibles 112200
  (112201, 'Gastos de Organización', 'activo', 'GtoIntan', FALSE, TRUE, FALSE),
  (112202, 'Amor. Acu. de Gastos de Organización', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112203, 'Crédito Mercantil', 'activo', 'GtoIntan', FALSE, TRUE, FALSE),
  (112204, 'Amor. Acu. de Crédito Mercantil', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112205, 'Derecho de Llave', 'activo', 'GtoIntan', FALSE, TRUE, FALSE),
  (112206, 'Amor. Acu. de Derecho de Llave', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112207, 'Renombre Comercial', 'activo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112208, 'Amor. Acu. de Renombre Comercial', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112209, 'Marcas y Patentes', 'activo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112210, 'Amor. Acu. de Marcas y Patentes', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112211, 'Patentes', 'activo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112212, 'Amor. Acu. de Patentes', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112213, 'Fórmulas Patentadas', 'activo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112214, 'Amor. Acu. de Fórmulas Patentadas', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112215, 'Gastos de Constitución', 'activo', 'GtoIntan', FALSE, TRUE, FALSE),
  (112216, 'Amor. Acu. de Gtos de Constitucion', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112217, 'Gastos de Instalación Fábrica', 'activo', 'GtoIntan', TRUE, TRUE, FALSE),
  (112218, 'Amor. Acu. Gastos de Instalación Fábrica', 'pasivo', 'GtoIntan', TRUE, FALSE, FALSE),
  (112219, 'Gastos de Instalación Sala de Ventas', 'activo', 'GtoIntan', FALSE, TRUE, FALSE),
  (112220, 'Amor. Acu. Gastos de Instalación Sala de Ventas', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112221, 'Gastos de Instalación Sala de Administración', 'activo', 'GtoIntan', FALSE, TRUE, FALSE),
  (112222, 'Amor. Acu. Gastos de Instalación Administración', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),
  (112223, 'Gastos de Instalación General', 'activo', 'GtoIntan', FALSE, TRUE, FALSE),
  (112224, 'Amor. Acu. Gastos de Instalación General', 'pasivo', 'GtoIntan', FALSE, FALSE, FALSE),

  -- Activo Gastos Diferidos
  (112301, 'Inve. en Valores a L P', 'activo', 'GtoDiferidos', FALSE, TRUE, FALSE),

  -- Pasivo Corriente
  (121001, 'Proveedores', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121002, 'Debito Fiscal', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121003, 'Doc. por Pagar a C/Plazo', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121004, 'Préstamos Banc C/Plazo', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121005, 'IGSS por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121006, 'Comi. Percibi no Deven', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121008, '(-) ISR Trimestral', 'activo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121009, 'Alquileres Percibidos por Anticipado', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121010, 'IUSI por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121011, 'Reserva para Indemnizaciones', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121012, 'ISR Retenido por Pagar Sobre Compras', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121013, 'Impuesto Sobre la Renta por Pagar', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121014, 'Ventas por Realizar', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121015, 'Hipotecas a Corto Plazo', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121016, 'Corresponsales', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121017, 'Comisiones Cobradas por Anticipado', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121018, 'Retenciones Laborales', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121019, 'Retención del Impuesto sobre la Renta', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121020, 'Socio X Cuenta Personal (A)', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121021, 'Socio X Cuenta Particular (A)', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121022, 'Sueldos por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121023, 'Timbre de Prensa Retenido', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121024, 'IVA por Acreditar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121025, 'IVA Debitable', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121026, 'IVA por Debitar', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121027, 'IVA Retenido sobre Facturas Especiales', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121028, 'IVA (acreedor)', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121029, 'Préstamos Bancarios', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121030, 'Préstamos Bancarios a Corto Plazo', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121031, 'Productos Percibidos no Devengados', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121032, 'Impuestos y Contribuciones por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121033, 'Impuesto Único sobre Inmuebles por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121035, 'ISO por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121036, 'ISR Retenido sobre Facturas Especiales', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121037, 'ISR Retenido Sobre Ganancias de Capital', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121038, 'ISR Retenido S/Compras por Pagar', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121039, 'ISR Retenido Sobre Pago de Dividendos', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121040, 'Impuesto sobre la Renta Retenido', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121041, 'Intereses Percibidos no Devengados', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121042, 'Intereses Cobrados por Anticipado', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121043, 'Intereses por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121044, 'IGSS Laboral', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121045, 'Dividendos no Retirados o no Pagados', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121046, 'Dividendos por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121047, 'Documentos Endosados', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121048, 'Documentos por Cobrar Descontados', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121049, 'Donativos por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121050, 'Efectos Descontados', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121051, 'Efectos Endosados', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121052, 'Efectos por Pagar a Corto Plazo', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121053, 'Cuotas Laborales por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121054, 'Cuotas Patronales por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121055, 'Depreciación Acumulada de todo activo', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121056, 'Anticipo sobre Ventas', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121057, 'Acreedores Hipotecarios', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121058, 'Acreedores por Prendas en Garantía P.C.', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121059, 'Alquileres Percibidos no Devengados', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121060, 'Alquileres por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121061, 'Amortizaciones Acumuladas (cualquiera)', 'pasivo', 'PasivoCorr', FALSE, FALSE, FALSE),
  (121062, 'Corresponsales (Acreedor)', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),
  (121063, 'Retenciones Judiciales por Pagar', 'pasivo', 'PasivoCorr', FALSE, TRUE, FALSE),

  -- Pasivo No Corriente
  (122001, 'Doc. por Pagar a L P', 'pasivo', 'PasivoNoCorr', FALSE, TRUE, FALSE),
  (122002, 'Hipotecas a Largo Plazo', 'pasivo', 'PasivoNoCorr', FALSE, TRUE, FALSE),
  (122003, 'Prestamos Bancarios L / P', 'pasivo', 'PasivoNoCorr', FALSE, TRUE, FALSE),
  (122004, 'Préstamos Bancarios a Largo Plazo', 'pasivo', 'PasivoNoCorr', FALSE, TRUE, FALSE),
  (122005, 'Hipotecas', 'pasivo', 'PasivoNoCorr', FALSE, TRUE, FALSE),
  (122006, 'Efectos por Pagar a Largo Plazo', 'pasivo', 'PasivoNoCorr', FALSE, TRUE, FALSE),
  (122007, 'Acreedores a Largo Plazo', 'pasivo', 'PasivoNoCorr', FALSE, TRUE, FALSE),

  -- Patrimonio Neto o Seccion del Capital Contable
  (131001, 'Capital', 'pasivo', 'PatriNeto', FALSE, TRUE, FALSE),
  (131002, 'Capital Autorizado', 'pasivo', 'PatriNeto', FALSE, TRUE, FALSE),
  (131003, '(-)Cuenta Personal', 'activo', 'PatriNeto', FALSE, TRUE, FALSE),
  (131004, 'Reserva Legal', 'pasivo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131005, 'Superávit Acumulado', 'pasivo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131006, 'Suscriptores de Acciones', 'activo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131007, 'Superávit por Revaluación de Activos', 'pasivo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131008, 'Señor X Cuenta Personal', 'activo', 'PatriNeto', FALSE, TRUE, FALSE),
  (131009, 'Señor X Cuenta Particular', 'activo', 'PatriNeto', FALSE, TRUE, FALSE),
  (131010, 'Socio X Cuenta Personal (D)', 'activo', 'PatriNeto', FALSE, TRUE, FALSE),
  (131011, 'Socio X Cuenta Particular (D)', 'activo', 'PatriNeto', FALSE, TRUE, FALSE),
  (131012, 'Socio X Cuenta Promesa', 'activo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131013, 'Acciones no Suscritas', 'activo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131014, 'Acciones por Suscribir', 'activo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131015, 'Acciones Suscritas', 'activo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131016, 'Utilidades no Distribuidas', 'pasivo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131017, 'Utilidad por Distribuir', 'pasivo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131018, 'Utilidades Retenidas', 'pasivo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131019, 'Pérdidas Acumuladas', 'activo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131020, 'Pérdida de Ejercicios Anteriores', 'activo', 'PatriNeto', FALSE, FALSE, FALSE),
  (131021, 'Prima sobre Acciones', 'pasivo', 'PatriNeto', FALSE, FALSE, FALSE),

  -- Ingresos Operativos e Imprevistos
  (210001, 'Ventas', 'ganancia', 'Ingresos', FALSE, TRUE, FALSE),
  (210002, '(-)Dev y Rebajas S/Ventas', 'perdida', 'Ingresos', FALSE, TRUE, FALSE),
  (210003, 'Alquileres Percibidos', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (210004, 'Descuentos sobre Acciones', 'perdida', 'Ingresos', FALSE, FALSE, FALSE),
  (210005, 'Descuentos sobre Ventas', 'perdida', 'Ingresos', FALSE, TRUE, FALSE),

  -- Inventarios Iniciales
  (220001, 'Inve. Ini de Mercaderías', 'perdida', 'InveIni', FALSE, TRUE, FALSE),
  (220002, 'Inv. Inicial Productos Terminados', 'perdida', 'InveIni', TRUE, TRUE, FALSE),

  -- Inventarios finales
  (220005, 'Inve. Final de Mercaderías', 'ganancia', 'InveFin', FALSE, TRUE, FALSE),

  -- Compras
  (220101, 'Compras', 'perdida', 'Compras', FALSE, TRUE, TRUE),
  (220102, 'Gastos sobre Compras', 'perdida', 'Compras', FALSE, TRUE, TRUE),
  (220103, 'Fletes sobre Compras', 'perdida', 'Compras', FALSE, TRUE, FALSE),
  (220104, 'Impuestos Aduaneros / Compras', 'perdida', 'Compras', FALSE, TRUE, TRUE),
  (220105, 'Comi. Banc. / Compras', 'perdida', 'Compras', FALSE, TRUE, TRUE),
  (220206, 'Dev. y Rev. / Compras', 'ganancia', 'Compras', FALSE, TRUE, TRUE),

  -- Gastos de Ventas
  (231001, 'Sueldos Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231002, 'Boni Incen Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231003, 'Cuo. Patro S/Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231004, 'Comisiones sobre Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, TRUE),
  (231005, 'Sueldos de Vendedores', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231006, 'Bonif. Incentivo de Vendedores', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231007, 'Prestaciones Laborales de Vendedores', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231008, 'Deprec. Mobiliario y Equipo S/Ventas', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231009, 'Deprec. Equipo de Computacón S/Ventas', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231010, 'Deprec. Sistemas Informáticos o Eq. de Comput. S/Ventas', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231012, 'Deprec. Edificios Sala de Ventas', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231013, 'Deprec. Vehículos Sala de Ventas', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231014, 'Deprec. Cristalería y Peltre Sala de Ventas','perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231015, 'Deprec. Útiles y Enseres Sala de Ventas','perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231016, 'IUSI Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231017, 'Propaganda', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231018, 'Publicidad', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231019, 'Reparación y Mantenimiento de Vehículos', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231020, 'Seguros Vencidos Sala de Ventas', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231022, 'Suministros Consumidos Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, TRUE),
  (231023, 'Primas de Seguro Vencidas Sala de Vtas.', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231024, 'Impuestos y Contribuciones Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231025, 'Impto. Único sobre Inmuebles Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231026, 'Indemnizaciones Sala de Ventas', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231027, 'Fuerza Motriz Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231028, 'Gastos Diversos Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231029, 'Gastos Misceláneos Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231030, 'Gastos Publicitarios', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231031,'Grasas y Aceites Consumidos Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, TRUE),
  (231032, 'Energía Eléctrica Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231033, 'Depreciación Construcción Sala de Vtas.', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231034, 'Aguinaldos Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231035, 'Alquiler Sala de Ventas', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),
  (231036, 'Amortización Gtos. Instalación Sala Vtas', 'perdida', 'GtoVentas', FALSE, FALSE, FALSE),
  (231055, 'Cuotas Patronales de Vendedores', 'perdida', 'GtoVentas', FALSE, TRUE, FALSE),

  -- Gastos de Administración
  (232001, 'Sueldos de Admón.', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232002, 'Boni Incentivo de Admon', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232003, 'Cuo Pat de Admon', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232004, 'Dep. Mob y Equi de Oficina', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232005, 'Dep Equi de Computación', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232006, 'Amor. Gtos de Organización', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232007, 'Papelería y Útiles Consumidos', 'perdida', 'GtoAdmin', FALSE, TRUE, TRUE),
  (232008, 'Cuentas Incobrables', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232009, 'Sueldos de Administración', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232010, 'Cuotas Patronales de Administración', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232012, 'Prestaciones Laborales de Admón.', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232013, 'Depreciación Edificios de Oficinas', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232014, 'Depreciación Vehículos de Oficinas', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232015, 'Deprec. Equipo de Comput. de Oficinas', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232017, 'Amortización Gastos de Organización', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232018, 'IUSI de Oficina', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232019, 'Impuesto Sobre la Renta', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232020, 'Derechos Arancelarios sobre Compras de Mercaderia', 'perdida', 'GtoAdmin', FALSE, TRUE, TRUE),
  (232021, 'Regalías', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232022, 'Seguros', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232023, 'Seguros Vencidos', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232024, 'Seguros Vencidos de Administración', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232026, 'Suministros Consumidos de Oficina', 'perdida', 'GtoAdmin', FALSE, TRUE, TRUE),
  (232027, 'Timbre de Prensa', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232028, 'Útiles y Enseres Consumidos', 'perdida', 'GtoAdmin', FALSE, TRUE, TRUE),
  (232029, 'Viáticos', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232030, 'Material de Empaque Consumido', 'perdida', 'GtoAdmin', FALSE, TRUE, TRUE),
  (232031, 'Mercaderías Inservibles o Estropeadas', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232033, 'Primas de Seguro Vencidas', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232034, 'Primas de Seguro Vencidas de Admón.', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232035, 'Impto. Único sobre Inmuebles de Admón.', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232036, 'ISR Sobre Ganancias de Capital', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232037, 'Indemnizaciones de Administración', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232038, 'Fuerza Motriz de Oficinas', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232039, 'Gastos Diversos de Administración', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232040, 'Gastos Generales', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232041, 'Gastos Misceláneos de Oficina', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232042, 'Donativos', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232043, 'Donativos Pagados', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232044, 'Energía Eléctrica de Oficina', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232045, 'Correo, Teléfono y Telégrafos', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232046, 'Cuotas Laborales', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232047, 'Depreciación Construcción de Oficina', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232048, 'Depreciación de Cristalería', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232049, 'Depreciación Sistemas Informáticos', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232050, 'Aguinaldos', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232051, 'Alquileres', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232052, 'Alquiler de Oficinas', 'perdida', 'GtoAdmin', FALSE, TRUE, FALSE),
  (232053, 'Amortización Crédito Mercantil', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232054, 'Amortización Derecho de Llave', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232055, 'Amortización Gastos de Constitución', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232056, 'Amortización Gtos. Instalación de Ofic.', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232057, 'Amortización Gastos de Organización', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232058, 'Amortización Marcas y Patentes', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232059, 'Amortización de Patentes', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232060, 'Amortización Renombre Comercial', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),
  (232061, 'Activos Inservibles', 'perdida', 'GtoAdmin', FALSE, FALSE, FALSE),

  -- Ingresos Financieros
  (240001, 'Intereses Percibidos', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240002, 'Intereses Devengados', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240003, 'Intereses Ganados', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240004, 'Intereses Percibidos o Producto', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240005, 'Descuentos Percibidos', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240006, 'Alquileres Cobrados', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240007, 'Alquileres Ganados', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240008, 'Alquileres Producto', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240009, 'Alquileres Devengados', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),
  (240010, 'Alquileres Percibidos', 'ganancia', 'IngrFina', FALSE, TRUE, FALSE),

  -- Gastos Financieros
  (250001, 'Intereses Gastos', 'perdida', 'GastosFina', FALSE, TRUE, FALSE),
  (250002, 'Multas y Recargos', 'perdida', 'GastosFina', FALSE, TRUE, FALSE),
  (250003, 'Intereses Gasto', 'perdida', 'GastosFina', FALSE, TRUE, FALSE),
  (250004, 'Descuentos Concedidos', 'perdida', 'GastosFina', FALSE, TRUE, FALSE),

  -- Otros Gastos Financieros
  (260001, 'Donativos', 'perdida', 'OtrosGtoFina', FALSE, TRUE, FALSE),
  (260002, 'Pérdida en Negociación de Activos', 'perdida', 'OtrosGtoFina', FALSE, FALSE, FALSE),

  -- Otros ingresos Financieros
  (270001, 'Comisiones Percibidas', 'ganancia', 'Otring', FALSE, TRUE, FALSE),
  (270002, 'ISR sobre Rentas de Capital', 'ganancia', 'Otring', FALSE, FALSE, FALSE),
  (270003, 'Recuperación de Créditos', 'ganancia', 'Otring', FALSE, TRUE, FALSE),
  (270004, 'Regalías Percibidas', 'ganancia', 'Otring', FALSE, TRUE, FALSE),
  (270005, 'Sobrantes de Caja', 'ganancia', 'Otring', FALSE, TRUE, FALSE),
  (270006, 'Faltante de Caja', 'perdida', 'Otring', FALSE, TRUE, FALSE),
  (270007, 'Ganancia en Negociación de Activos', 'ganancia', 'Otring', FALSE, FALSE, FALSE),
  (270008, 'Ganancia en Venta de Activos', 'ganancia', 'Otring', FALSE, TRUE, FALSE),
  (270009, 'Dividendos Percibidos', 'ganancia', 'Otring', FALSE, TRUE, FALSE),
  (270010, 'Dividendos Ganados', 'ganancia', 'Otring', FALSE, TRUE, FALSE),
  (270011, 'Donativos Percibidos', 'ganancia', 'Otring', FALSE, TRUE, FALSE),

  -- Costos de Producción: Materiales Directos
  (310100, 'Inventario Inicial de Materia Prima', 'costo_debe', 'MaterialesDirectos', TRUE, TRUE, TRUE),
  (310200, 'Compras de Materia Prima (Locales)', 'costo_debe', 'MaterialesDirectos', TRUE, TRUE, TRUE),
  (310300, 'Compras de Materia Prima (Importaciones)', 'costo_debe', 'MaterialesDirectos', TRUE, TRUE, TRUE),
  (310400, 'Impuestos Aduaneros / Aranceles', 'costo_debe', 'MaterialesDirectos', TRUE, TRUE, TRUE),
  (310500, 'Fletes y Seguros de Importación', 'costo_debe', 'MaterialesDirectos', TRUE, TRUE, TRUE),
  (310600, 'Gastos de Desaduanaje', 'costo_debe', 'MaterialesDirectos', TRUE, TRUE, TRUE),
  (310700, '(-) Devoluciones y Rebajas sobre Compras', 'costo_haber', 'MaterialesDirectos', TRUE, TRUE, TRUE),
  (310800, '(-) Inventario Final de Materia Prima', 'costo_haber', 'MaterialesDirectos', TRUE, TRUE, TRUE),

  -- Costos de Producción: Mano de Obra
  (320100, 'Sueldos y Salarios', 'costo_debe', 'ManoObra', TRUE, TRUE, FALSE),
  (320200, 'Prestaciones Sociales y Cargas Patronales', 'costo_debe', 'ManoObra', TRUE, TRUE, FALSE),
  (320300, 'Horas Extra Directas', 'costo_debe', 'ManoObra', TRUE, TRUE, FALSE),

  -- Costos de Producción: Costos Indirectos de Fabricación (CIF)
  (330100, 'Materiales Indirectos y Suministros', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, FALSE),
  (330101, 'Envases en Departamento de Producción', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, FALSE),
  (330200, 'Mano de Obra Indirecta (Supervisión)', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, FALSE),
  (330300, 'Depreciaciones Maquinaria y Planta', 'costo_debe', 'CostosIndirectos', TRUE, FALSE, FALSE),
  (330400, 'Servicios Públicos de Fábrica', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, FALSE),
  (330401, 'Fuerza Motriz', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, FALSE),
  (330500, 'Alquileres y Seguros de Planta', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, FALSE),
  (330501, 'Gastos de Instalación Fábrica', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, FALSE),
  (330600, 'Bonificación Incentivo Fábrica', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, FALSE),
  (330700, 'Reparación y Mantenimiento de Maquinaria', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, TRUE),
  (330800, 'Depreciación Útiles y Enseres Fábrica', 'costo_debe', 'CostosIndirectos', TRUE, FALSE, FALSE),
  (330900, 'Grasas y Aceites Consumidos Fábrica', 'costo_debe', 'CostosIndirectos', TRUE, TRUE, TRUE),
  (331000, 'Amortización Gastos de Instalación Fábrica', 'costo_debe', 'CostosIndirectos', TRUE, FALSE, FALSE),

  -- Costos de Producción: Cuentas de Inventarios Mecánicos
  (340101, 'Inventario Inicial Artículos en Proceso', 'costo_debe', 'CuentasInventarios', TRUE, TRUE, FALSE),
  (340102, 'Inventario Inicial Artículos Terminados', 'costo_debe', 'CuentasInventarios', TRUE, TRUE, FALSE),
  (340201, '(-) Inventario Final en Proceso', 'costo_haber', 'CuentasInventarios', TRUE, TRUE, FALSE),
  (340202, '(-) Inventario Final Artículos Terminados', 'costo_haber', 'CuentasInventarios', TRUE, TRUE, FALSE);
