INSERT INTO "public"."nomenclatura" ("codigo", "nombre", "saldo", "categoria", "es_costo", "es_efectivo", "es_variable") VALUES
(111101, 'Caja y Bancos', 'activo', 'Disponible', false, true, false),
(111102, 'Bancos', 'activo', 'Disponible', false, true, false),
(111103, 'Caja', 'activo', 'Disponible', false, true, false),
(111104, 'Caja Chica', 'activo', 'Disponible', false, true, false),
(111105, 'Fondo Fijo', 'activo', 'Disponible', false, true, false),
(111106, 'Divisas Adquiridas', 'activo', 'Disponible', false, true, false),
(111107, 'Especies Fiscales', 'activo', 'Disponible', false, true, false),
(111108, 'Caja Chica de Fábrica', 'activo', 'Disponible', false, true, false),
(111201, 'Deudores no Comerciales', 'activo', 'Exigible', false, true, false),
(111202, 'Documentos por Cobrar', 'activo', 'Exigible', false, true, false),
(111203, 'Clientes', 'activo', 'Exigible', false, true, false),
(111204, '(-)Reserva para Cuentas Incobrables', 'pasivo', 'Exigible', false, true, false),
(111205, 'Anticipo sobre Compras', 'activo', 'Exigible', false, true, false),
(111206, 'Crédito Fiscal', 'activo', 'Exigible', false, false, false),
(111207, 'Documentos por Cobrar a Corto Plazo', 'activo', 'Exigible', false, true, false),
(111208, 'ISR Retenido por Acreditar Sobre Ventas', 'activo', 'Exigible', false, false, false),
(111209, '(-) Documentos Descontados', 'pasivo', 'Exigible', false, true, false),
(111210, 'Productos por Cobrar', 'activo', 'Exigible', false, false, false),
(111211, 'Propaganda Pagada por Anticipado', 'activo', 'Exigible', false, true, false),
(111212, 'Publicidad Pagada por Anticipado', 'activo', 'Exigible', false, true, false),
(111213, 'Seguros Anticipados', 'activo', 'Exigible', false, true, false),
(111214, 'Seguros Pagados por Anticipado', 'activo', 'Exigible', false, true, false),
(111215, 'Seguros no Vencidos', 'activo', 'Exigible', false, false, false),
(111216, 'Señor X Cuenta Personal', 'activo', 'Exigible', false, true, false),
(111217, 'Señor X Cuenta Particular', 'activo', 'Exigible', false, true, false),
(111218, 'Socio X Cuenta Personal (D)', 'activo', 'Exigible', false, true, false),
(111219, 'Socio X Cuenta Particular (D)', 'activo', 'Exigible', false, true, false),
(111220, 'Socio X Cuenta Promesa', 'activo', 'Exigible', false, false, false),
(111221, 'Sueldos Pagados por Anticipado', 'activo', 'Exigible', false, true, false),
(111222, 'Valores Mobiliarios', 'activo', 'Exigible', false, true, false),
(111223, 'Valores Mobiliarios a Corto Plazo', 'activo', 'Exigible', false, true, false),
(111224, 'Valores Mobiliarios a Largo Plazo', 'activo', 'Exigible', false, true, false),
(111225, 'IVA por Cobrar', 'activo', 'Exigible', false, false, false),
(111226, 'IVA (deudor)', 'activo', 'Exigible', false, false, false),
(111227, 'Portafolio de Inversiones a Corto Plazo', 'activo', 'Exigible', false, true, false),
(111228, 'Portafolio de Inversiones a Largo Plazo', 'activo', 'Exigible', false, true, false),
(111229, 'Primas de Seguro no Vencidas', 'activo', 'Exigible', false, false, false),
(111230, 'Impuesto sobre la Renta Pag. por Anticipado', 'activo', 'Exigible', false, true, false),
(111231, 'ISO por Acreditar', 'activo', 'Exigible', false, true, false),
(111232, 'ISR Retenido S/Ventas por Acreditar', 'activo', 'Exigible', false, false, false),
(111233, 'Intereses por Cobrar', 'activo', 'Exigible', false, true, false),
(111234, 'Intereses Pagados por Anticipado', 'activo', 'Exigible', false, true, false),
(111235, 'Inversiones', 'activo', 'Exigible', false, true, false),
(111236, 'Inversiones a Corto Plazo', 'activo', 'Exigible', false, true, false),
(111237, 'Inversiones en Bonos a Corto Plazo', 'activo', 'Exigible', false, true, false),
(111238, 'Inversiones en Bonos a Largo Plazo', 'activo', 'Exigible', false, true, false),
(111239, 'Inversiones Financieras a Corto Plazo', 'activo', 'Exigible', false, true, false),
(111240, 'Inversiones Financieras a Largo Plazo', 'activo', 'Exigible', false, true, false),
(111241, 'Inversiones a Largo Plazo', 'activo', 'Exigible', false, true, false),
(111242, 'Inversiones en Valores', 'activo', 'Exigible', false, true, false),
(111243, 'Inversiones en Valores a Corto Plazo', 'activo', 'Exigible', false, true, false),
(111244, 'Inversiones en Valores a Largo Plazo', 'activo', 'Exigible', false, true, false),
(111245, 'Deudores Diversos', 'activo', 'Exigible', false, true, false),
(111246, 'Deudores Empleados', 'activo', 'Exigible', false, true, false),
(111247, 'Deudores Varios', 'activo', 'Exigible', false, true, false),
(111248, 'Dividendos por Cobrar', 'activo', 'Exigible', false, true, false),
(111249, 'Documentos por Cobrar a corto y a largo plazo', 'activo', 'Exigible', false, false, false),
(111250, 'Efectos por Cobrar', 'activo', 'Exigible', false, false, false),
(111251, 'Corresponsales (deudor)', 'activo', 'Exigible', false, true, false),
(111252, 'Cuenta Promesa', 'activo', 'Exigible', false, false, false),
(111253, 'Depósitos en Garantía', 'activo', 'Exigible', false, true, false),
(111254, 'Anticipo de Clientes', 'activo', 'Exigible', false, true, false),
(111255, 'Anticipo a Proveedores', 'activo', 'Exigible', false, true, false),
(111256, 'Acciones Adquiridas', 'activo', 'Exigible', false, true, false),
(111257, 'Acciones no Suscritas', 'activo', 'Exigible', false, false, false),
(111258, 'Acciones por Suscribir', 'activo', 'Exigible', false, false, false),
(111259, 'Acciones Suscritas', 'activo', 'Exigible', false, false, false),
(111260, 'Valores de Inmediata Realización', 'activo', 'Exigible', false, true, false),
(111261, 'Documentos por Cobrar a Largo Plazo', 'activo', 'Exigible', false, false, false),
(111301, 'Mercaderias', 'activo', 'Realisable', false, true, false),
(111302, 'Papelería y útiles', 'activo', 'Realisable', false, true, false),
(111303, 'Materia Prima', 'activo', 'Realisable', true, true, true),
(111304, 'Productos en Proceso', 'activo', 'Realisable', true, true, false),
(111305, 'Productos Terminados', 'activo', 'Realisable', true, true, false),
(111306, 'Papelería y Útiles (existencia)', 'activo', 'Realisable', false, false, false),
(111307, 'Mercaderías Enviadas en Consignación', 'activo', 'Realisable', false, false, false),
(111308, 'Material de Empaque', 'activo', 'Realisable', false, true, true),
(112101, 'Mobiliario y Equipo', 'activo', 'PropPlanEqui', false, true, false),
(112102, '(-) Deprec. Acu. Mobiliario y Equipo', 'activo', 'PropPlanEqui', false, false, false),
(112103, 'Equipo de Computo', 'activo', 'PropPlanEqui', false, true, false),
(112104, '(-) Deprec. Acu. de Equipo de Computacón', 'activo', 'PropPlanEqui', false, false, false),
(112105, 'Sistemas Informáticos o Eq. de Comput.', 'activo', 'PropPlanEqui', false, true, false),
(112106, '(-) Deprec. Acu. Edificios', 'activo', 'PropPlanEqui', false, false, false),
(112108, '(-) Dep. Acu. Vehículos', 'activo', 'PropPlanEqui', false, false, false),
(112109, 'Terrenos', 'activo', 'PropPlanEqui', false, true, false),
(112110, 'Vehículos', 'activo', 'PropPlanEqui', false, true, false),
(112111, 'Vehículos de Reparto', 'activo', 'PropPlanEqui', false, true, false),
(112112, 'Maquinaria', 'activo', 'PropPlanEqui', false, true, false),
(112113, 'Herramientas', 'activo', 'PropPlanEqui', false, true, false),
(112114, 'Edificios de Fábrica', 'activo', 'PropPlanEqui', false, true, false),
(112115, '(-) Deprec. Acu. Edificios de Fábrica', 'pasivo', 'PropPlanEqui', false, false, false),
(112116, '(-) Deprec. Acu. Maquinaria', 'pasivo', 'PropPlanEqui', false, false, false),
(112117, '(-) Deprec. Acu. Herramientas', 'pasivo', 'PropPlanEqui', false, false, false),
(112118, 'Cristalería y Peltre', 'activo', 'PropPlanEqui', false, true, false),
(112119, 'Útiles y Enseres', 'activo', 'PropPlanEqui', false, true, false),
(112120, '(-) Deprec. Acu. Útiles y Enseres', 'pasivo', 'PropPlanEqui', false, false, false),
(112135, 'Terrenos', 'activo', 'PropPlanEqui', false, true, false),
(112136, 'Edificios', 'activo', 'PropPlanEqui', false, true, false),
(112137, 'Vehículos', 'activo', 'PropPlanEqui', false, true, false),
(112138, 'Inmuebles', 'activo', 'PropPlanEqui', false, true, false),
(112201, 'Gastos de Organización', 'activo', 'GtoIntan', false, true, false),
(112202, 'Amor. Acu. de Gtos de Organ', 'pasivo', 'GtoIntan', false, false, false),
(112203, 'Renombre Comercial', 'activo', 'GtoIntan', false, false, false),
(112204, 'Marcas y Patentes', 'activo', 'GtoIntan', false, false, false),
(112205, 'Patentes', 'activo', 'GtoIntan', false, false, false),
(112206, 'Fórmulas Patentadas', 'activo', 'GtoIntan', false, false, false),
(112207, 'Gastos de Constitución', 'activo', 'GtoIntan', false, true, false),
(112208, 'Gastos de Instalación', 'activo', 'GtoIntan', false, true, false),
(112209, 'Derecho de Llave', 'activo', 'GtoIntan', false, false, false),
(112301, 'Inve. en Valores a L P', 'activo', 'GtoDiferidos', false, true, false),
(121001, 'Proveedores', 'pasivo', 'PasivoCorr', false, true, false),
(121002, 'Debito Fiscal', 'activo', 'PasivoCorr', false, true, false),
(121003, 'Doc. por Pagar a C/Plazo', 'pasivo', 'PasivoCorr', false, true, false),
(121004, 'Préstamos Banc C/Plazo', 'pasivo', 'PasivoCorr', false, true, false),
(121005, 'IGSS por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121006, 'Comi. Percibi no Deven', 'pasivo', 'PasivoCorr', false, true, false),
(121008, '(-) ISR Trimestral', 'activo', 'PasivoCorr', false, true, false),
(121009, 'Alquileres Percibidos por Anticipado', 'pasivo', 'PasivoCorr', false, true, false),
(121010, 'IUSI por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121011, 'Reserva para Indemnizaciones', 'pasivo', 'PasivoCorr', false, false, false),
(121012, 'ISR Retenido por Pagar Sobre Compras', 'pasivo', 'PasivoCorr', false, false, false),
(121013, 'Impuesto Sobre la Renta por Pagar', 'pasivo', 'PasivoCorr', false, false, false),
(121014, 'Ventas por Realizar', 'pasivo', 'PasivoCorr', false, false, false),
(121015, 'Hipotecas a Corto Plazo', 'pasivo', 'PasivoCorr', false, true, false),
(121016, 'Corresponsales', 'pasivo', 'PasivoCorr', false, true, false),
(121017, 'Comisiones Cobradas por Anticipado', 'pasivo', 'PasivoCorr', false, true, false),
(121018, 'Provisión para Cuentas Incobrables', 'pasivo', 'PasivoCorr', false, false, false),
(121019, 'Provisión para Cuentas Malas', 'pasivo', 'PasivoCorr', false, false, false),
(121020, 'Provisión para Cuentas de Difícil Cobro', 'pasivo', 'PasivoCorr', false, false, false),
(121021, 'Provisión para Cuentas Morosas', 'pasivo', 'PasivoCorr', false, false, false),
(121022, 'Reserva para Cuentas Incobrables', 'pasivo', 'PasivoCorr', false, false, false),
(121023, 'Reserva para Cuentas Malas', 'pasivo', 'PasivoCorr', false, false, false),
(121024, 'Reserva para Cuentas Morosas', 'pasivo', 'PasivoCorr', false, false, false),
(121025, 'Reserva para Cuentas de Difícil Cobro', 'pasivo', 'PasivoCorr', false, false, false),
(121026, 'Retenciones Laborales', 'pasivo', 'PasivoCorr', false, true, false),
(121027, 'Retención del Impuesto sobre la Renta', 'pasivo', 'PasivoCorr', false, true, false),
(121028, 'Socio X Cuenta Personal (A)', 'pasivo', 'PasivoCorr', false, true, false),
(121029, 'Socio X Cuenta Particular (A)', 'pasivo', 'PasivoCorr', false, true, false),
(121030, 'Sueldos por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121031, 'Timbre de Prensa Retenido', 'pasivo', 'PasivoCorr', false, true, false),
(121032, 'Ventas por Realizar', 'pasivo', 'PasivoCorr', false, false, false),
(121033, 'IVA por Acreditar', 'pasivo', 'PasivoCorr', false, true, false),
(121034, 'IVA Debitable', 'pasivo', 'PasivoCorr', false, false, false),
(121035, 'IVA por Debitar', 'pasivo', 'PasivoCorr', false, false, false),
(121036, 'IVA Retenido sobre Facturas Especiales', 'pasivo', 'PasivoCorr', false, false, false),
(121037, 'IVA (acreedor)', 'pasivo', 'PasivoCorr', false, false, false),
(121038, 'Préstamos Bancarios', 'pasivo', 'PasivoCorr', false, true, false),
(121039, 'Préstamos Bancarios a Corto Plazo', 'pasivo', 'PasivoCorr', false, true, false),
(121040, 'Productos Percibidos no Devengados', 'pasivo', 'PasivoCorr', false, false, false),
(121041, 'Impuestos y Contribuciones por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121042, 'Impuesto Único sobre Inmuebles por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121043, 'Impuesto sobre la Renta por Pagar', 'pasivo', 'PasivoCorr', false, false, false),
(121044, 'ISO por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121045, 'ISR Retenido sobre Facturas Especiales', 'pasivo', 'PasivoCorr', false, false, false),
(121046, 'ISR Retenido Sobre Ganancias de Capital', 'pasivo', 'PasivoCorr', false, false, false),
(121047, 'ISR Retenido S/Compras por Pagar', 'pasivo', 'PasivoCorr', false, false, false),
(121048, 'ISR Retenido Sobre Pago de Dividendos', 'pasivo', 'PasivoCorr', false, false, false),
(121049, 'Impuesto sobre la Renta Retenido', 'pasivo', 'PasivoCorr', false, false, false),
(121050, 'Intereses Percibidos no Devengados', 'pasivo', 'PasivoCorr', false, false, false),
(121051, 'Intereses Cobrados por Anticipado', 'pasivo', 'PasivoCorr', false, true, false),
(121052, 'Intereses por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121053, 'Ganancia Pre-impuesto', 'pasivo', 'PasivoCorr', false, false, false),
(121054, 'Ganancia Pre-impuesto y Reserva', 'pasivo', 'PasivoCorr', false, false, false),
(121055, 'Ganancia Antes del Impuesto', 'pasivo', 'PasivoCorr', false, false, false),
(121056, 'Ganancia Antes del Impuesto y Reserva', 'pasivo', 'PasivoCorr', false, false, false),
(121057, 'Ganancia Post-Impuesto', 'pasivo', 'PasivoCorr', false, false, false),
(121058, 'Ganancia Post-Impuesto y Reserva', 'pasivo', 'PasivoCorr', false, false, false),
(121059, 'Ganancia Después del Impuesto', 'pasivo', 'PasivoCorr', false, false, false),
(121060, 'Ganancia Después del Impuesto y Reserva', 'pasivo', 'PasivoCorr', false, false, false),
(121061, 'IGSS Laboral', 'pasivo', 'PasivoCorr', false, true, false),
(121062, 'Dividendos no Retirados o no Pagados', 'pasivo', 'PasivoCorr', false, true, false),
(121063, 'Dividendos por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121064, 'Documentos Endosados', 'pasivo', 'PasivoCorr', false, true, false),
(121065, 'Documentos por Cobrar Descontados', 'pasivo', 'PasivoCorr', false, true, false),
(121066, 'Donativos por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121067, 'Efectos Descontados', 'pasivo', 'PasivoCorr', false, true, false),
(121068, 'Efectos Endosados', 'pasivo', 'PasivoCorr', false, true, false),
(121069, 'Efectos por Pagar a Corto Plazo', 'pasivo', 'PasivoCorr', false, true, false),
(121070, 'Estimación para Cuentas Incobrables', 'pasivo', 'PasivoCorr', false, false, false),
(121071, 'Estimación para Cuentas Malas', 'pasivo', 'PasivoCorr', false, false, false),
(121072, 'Estimación para Cuentas Dudosas', 'pasivo', 'PasivoCorr', false, false, false),
(121073, 'Estimación para Cuentas de Difícil Cobro', 'pasivo', 'PasivoCorr', false, false, false),
(121074, 'Cuotas Laborales por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121075, 'Cuotas Patronales por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121076, 'Depreciación Acumulada de todo activo', 'pasivo', 'PasivoCorr', false, false, false),
(121077, 'Anticipo sobre Ventas', 'pasivo', 'PasivoCorr', false, true, false),
(121078, 'Acreedores Hipotecarios', 'pasivo', 'PasivoCorr', false, true, false),
(121079, 'Acreedores por Prendas en Garantía P.C.', 'pasivo', 'PasivoCorr', false, true, false),
(121080, 'Alquileres Percibidos no Devengados', 'pasivo', 'PasivoCorr', false, false, false),
(121081, 'Alquileres por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(121082, 'Amortizaciones Acumuladas (cualquiera)', 'pasivo', 'PasivoCorr', false, false, false),
(121083, 'Corresponsales (Acreedor)', 'pasivo', 'PasivoCorr', false, true, false),
(121084, 'Retenciones Judiciales por Pagar', 'pasivo', 'PasivoCorr', false, true, false),
(122001, 'Doc. por Pagar a L P', 'pasivo', 'PasivoNoCorr', false, true, false),
(122002, 'Hipotecas a Largo Plazo', 'pasivo', 'PasivoNoCorr', false, true, false),
(122003, 'Prestamos Bancarios L / P', 'pasivo', 'PasivoNoCorr', false, true, false),
(122004, 'Préstamos Bancarios a Largo Plazo', 'pasivo', 'PasivoNoCorr', false, true, false),
(122005, 'Hipotecas', 'pasivo', 'PasivoNoCorr', false, true, false),
(122006, 'Efectos por Pagar a Largo Plazo', 'pasivo', 'PasivoNoCorr', false, true, false),
(122007, 'Acreedores a Largo Plazo', 'pasivo', 'PasivoNoCorr', false, true, false),
(131001, 'Capital', 'pasivo', 'PatriNeto', false, true, false),
(131003, '(-)Cuenta Personal', 'activo', 'PatriNeto', false, true, false),
(131004, 'Reserva Legal', 'pasivo', 'PatriNeto', false, false, false),
(131005, 'Superávit Acumulado', 'pasivo', 'PatriNeto', false, false, false),
(131006, 'Suscriptores de Acciones', 'activo', 'PatriNeto', false, false, false),
(131007, 'Superávit por Revaluación de Activos', 'pasivo', 'PatriNeto', false, false, false),
(131008, 'Utilidad del Ejercicio', 'pasivo', 'PatriNeto', false, false, false),
(131009, 'Utilidades no Distribuidas', 'pasivo', 'PatriNeto', false, false, false),
(131010, 'Utilidad por Distribuir', 'pasivo', 'PatriNeto', false, false, false),
(131011, 'Utilidades Retenidas', 'pasivo', 'PatriNeto', false, false, false),
(131012, 'Pérdidas Acumuladas', 'activo', 'PatriNeto', false, false, false),
(131013, 'Pérdida de Ejercicios Anteriores', 'activo', 'PatriNeto', false, false, false),
(131014, 'Pérdida del Ejercicio', 'activo', 'PatriNeto', false, false, false),
(131015, 'Prima sobre Acciones', 'pasivo', 'PatriNeto', false, false, false),
(210001, 'Ventas', 'ganancia', 'Ingresos', false, true, false),
(210002, '(-)Dev y Rebajas S/Ventas', 'perdida', 'Ingresos', false, true, false),
(210003, 'Alquileres Percibidos', 'activo', 'IngrFina', false, true, false),
(210004, 'Descuentos sobre Acciones', 'perdida', 'Ingresos', false, false, false),
(210005, 'Descuentos sobre Ventas', 'perdida', 'Ingresos', false, true, false),
(220001, 'Inve. Ini de Mercaderías', 'perdida', 'InveIni', false, true, false),
(220002, 'Inv. Inicial Productos Terminados', 'perdida', 'InveIni', true, true, false),
(220005, 'Inve. Final de Mercaderías', 'ganancia', 'InveFin', false, true, false),
(220101, 'Compras', 'perdida', 'Compras', false, true, true),
(220151, 'Gastos sobre Compras', 'perdida', 'Compras', false, true, true),
(220152, 'Fletes sobre Compras', 'perdida', 'Compras', false, true, false),
(220153, 'Impuestos Aduaneros / Compras', 'perdida', 'Compras', false, true, true),
(220154, 'Comi. Banc. / Compras', 'perdida', 'Compras', false, true, true),
(220201, 'Dev. y Rev. / Compras', 'ganancia', 'Compras', false, true, true),
(231001, 'Sueldos Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231002, 'Boni Incen Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231003, 'Cuo. Patro S/Ventas', 'perdida', 'GtoVentas', false, true, false),
(231004, 'Deprec. Mobiliario y Equipo S/Ventas', 'perdida', 'GtoVentas', false, false, false),
(231005, 'Comisiones sobre Ventas', 'perdida', 'GtoVentas', false, true, true),
(231006, 'Sueldos de Vendedores', 'perdida', 'GtoVentas', false, true, false),
(231007, 'Bonif. Incentivo de Vendedores', 'perdida', 'GtoVentas', false, true, false),
(231008, 'Prestaciones Laborales de Vendedores', 'perdida', 'GtoVentas', false, false, false),
(231009, 'Depreciación Edificios Sala de Ventas', 'perdida', 'GtoVentas', false, false, false),
(231010, 'Depreciación Vehículos Sala de Ventas', 'perdida', 'GtoVentas', false, false, false),
(231011, 'IUSI Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231012, 'Propaganda', 'perdida', 'GtoVentas', false, true, false),
(231013, 'Publicidad', 'perdida', 'GtoVentas', false, true, false),
(231014, 'Reparación y Mantenimiento de Vehículos', 'perdida', 'GtoVentas', false, true, false),
(231015, 'Seguros Vencidos Sala de Ventas', 'perdida', 'GtoVentas', false, false, false),
(231016, 'Sueldos de Vendedores', 'perdida', 'GtoVentas', false, true, false),
(231017, 'Suministros Consumidos Sala de Ventas', 'perdida', 'GtoVentas', false, true, true),
(231018, 'Primas de Seguro Vencidas Sala de Vtas.', 'perdida', 'GtoVentas', false, false, false),
(231019, 'Impuestos y Contribuciones Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231020, 'Impto. Único sobre Inmuebles Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231021, 'Indemnizaciones Sala de Ventas', 'perdida', 'GtoVentas', false, false, false),
(231022, 'Fuerza Motriz Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231023, 'Gastos Diversos Sala de Ventas', 'perdida', 'GtoVentas', false, true, false), 
(231024, 'Gastos Misceláneos Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231025, 'Gastos Publicitarios', 'perdida', 'GtoVentas', false, true, false),
(231026, 'Grasas y Aceites Consumidos Sala de Ventas', 'perdida', 'GtoVentas', false, true, true),
(231027, 'Energía Eléctrica Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231028, 'Depreciación Construcción Sala de Vtas.', 'perdida', 'GtoVentas', false, false, false),
(231029, 'Aguinaldos Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231030, 'Alquiler Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(231031, 'Amortización Gtos. Instalación Sala Vtas', 'perdida', 'GtoVentas', false, false, false),
(232001, 'Sueldos de Admón.', 'perdida', 'GtoAdmin', false, true, false),
(232002, 'Boni Incentivo de Admon', 'perdida', 'GtoAdmin', false, true, false),
(232003, 'Cuo Pat de Admon', 'perdida', 'GtoAdmin', false, true, false),
(232004, 'Dep. Mob y Equi de Oficina', 'perdida', 'GtoAdmin', false, false, false),
(232005, 'Dep Equi de Computación', 'perdida', 'GtoAdmin', false, false, false),
(232006, 'Amor. Gtos de Organización', 'perdida', 'GtoAdmin', false, false, false),
(232007, 'Pap y Utiles Consumidos', 'perdida', 'GtoAdmin', false, true, true),
(232008, 'Cuentas Incobrables', 'perdida', 'GtoAdmin', false, false, false),
(232009, 'Sueldos de Administración', 'perdida', 'GtoAdmin', false, true, false),
(232010, 'Cuotas Patronales de Administración', 'perdida', 'GtoAdmin', false, true, false),
(232011, 'Cuotas Patronales de Vendedores', 'perdida', 'GtoVentas', false, true, false),
(232012, 'Prestaciones Laborales de Admón.', 'perdida', 'GtoAdmin', false, false, false),
(232013, 'Depreciación Edificios de Oficinas', 'perdida', 'GtoAdmin', false, false, false),
(232014, 'Depreciación Vehículos de Oficinas', 'perdida', 'GtoAdmin', false, false, false),
(232015, 'Deprec. Equipo de Comput. de Oficinas', 'perdida', 'GtoAdmin', false, false, false),
(232016, 'Deprec. Equipo de Comput. Sala de Ventas', 'perdida', 'GtoVentas', false, false, false),
(232018, 'Amortización Gastos de Organización', 'perdida', 'GtoAdmin', false, false, false),
(232019, 'IUSI de Oficina', 'perdida', 'GtoAdmin', false, true, false), 
(232020, 'Impuesto Sobre la Renta', 'perdida', 'GtoAdmin', false, false, false),
(232021, 'Derechos Arancelarios sobre Compras', 'perdida', 'GtoAdmin', false, true, true),
(232022, 'Regalías', 'perdida', 'GtoAdmin', false, true, false),
(232023, 'Seguros', 'perdida', 'GtoAdmin', false, true, false),
(232024, 'Seguros Vencidos', 'perdida', 'GtoAdmin', false, false, false),
(232025, 'Seguros Vencidos de Administración', 'perdida', 'GtoAdmin', false, false, false),
(232026, 'Sueldos Sala de Ventas', 'perdida', 'GtoVentas', false, true, false),
(232027, 'Suministros Consumidos de Oficina', 'perdida', 'GtoAdmin', false, true, true),
(232028, 'Timbre de Prensa', 'perdida', 'GtoAdmin', false, true, false),
(232029, 'Útiles y Enseres Consumidos', 'perdida', 'GtoAdmin', false, true, true),
(232030, 'Viáticos', 'perdida', 'GtoAdmin', false, true, false),
(232031, 'Material de Empaque Consumido', 'perdida', 'GtoAdmin', false, true, true),
(232032, 'Mercaderías Inservibles o Estropeadas', 'perdida', 'GtoAdmin', false, false, false),
(232033, 'Papelería y Útiles Consumidos', 'perdida', 'GtoAdmin', false, true, true),
(232034, 'Primas de Seguro Vencidas', 'perdida', 'GtoAdmin', false, false, false),
(232035, 'Primas de Seguro Vencidas de Admón.', 'perdida', 'GtoAdmin', false, false, false),
(232036, 'Impto. Único sobre Inmuebles de Admón.', 'perdida', 'GtoAdmin', false, true, false),
(232037, 'ISR Sobre Ganancias de Capital', 'perdida', 'GtoAdmin', false, false, false),
(232038, 'Indemnizaciones de Administración', 'perdida', 'GtoAdmin', false, false, false),
(232039, 'Fuerza Motriz de Oficinas', 'perdida', 'GtoAdmin', false, true, false),
(232040, 'Gastos Diversos de Administración', 'perdida', 'GtoAdmin', false, true, false),
(232041, 'Gastos Generales', 'perdida', 'GtoAdmin', false, true, false),
(232042, 'Gastos Misceláneos de Oficina', 'perdida', 'GtoAdmin', false, true, false),
(232043, 'Donativos', 'perdida', 'GtoAdmin', false, true, false),
(232044, 'Donativos Pagados', 'perdida', 'GtoAdmin', false, true, false),
(232045, 'Energía Eléctrica de Oficina', 'perdida', 'GtoAdmin', false, true, false),
(232046, 'Correo, Teléfono y Telégrafos', 'perdida', 'GtoAdmin', false, true, false),
(232047, 'Cuotas Laborales', 'perdida', 'GtoAdmin', false, true, false),
(232048, 'Depreciación Construcción de Oficina', 'perdida', 'GtoAdmin', false, false, false),
(232049, 'Depreciación de Cristalería', 'perdida', 'GtoAdmin', false, false, false),
(232050, 'Depreciación Sistemas Informáticos', 'perdida', 'GtoAdmin', false, false, false),
(232051, 'Aguinaldos', 'perdida', 'GtoAdmin', false, true, false),
(232052, 'Alquileres', 'perdida', 'GtoAdmin', false, true, false),
(232053, 'Alquiler de Oficinas', 'perdida', 'GtoAdmin', false, true, false),
(232054, 'Amortización Crédito Mercantil', 'perdida', 'GtoAdmin', false, false, false),
(232055, 'Amortización Derecho de Llave', 'perdida', 'GtoAdmin', false, false, false),
(232056, 'Amortización Gastos de Constitución', 'perdida', 'GtoAdmin', false, false, false),
(232057, 'Amortización Gtos. Instalación de Ofic.', 'perdida', 'GtoAdmin', false, false, false),
(232058, 'Amortización Gastos de Organización', 'perdida', 'GtoAdmin', false, false, false),
(232059, 'Amortización Marcas y Patentes', 'perdida', 'GtoAdmin', false, false, false),
(232060, 'Amortización de Patentes', 'perdida', 'GtoAdmin', false, false, false),
(232061, 'Amortización Renombre Comercial', 'perdida', 'GtoAdmin', false, false, false),
(232062, 'Activos Inservibles', 'perdida', 'GtoAdmin', false, false, false),
(240001, 'Intereses Percibidos', 'ganancia', 'IngrFina', false, true, false),
(240002, 'Intereses Devengados', 'ganancia', 'IngrFina', false, true, false),
(240003, 'Intereses Ganados', 'ganancia', 'IngrFina', false, true, false),
(240004, 'Intereses Percibidos o Producto', 'ganancia', 'IngrFina', false, true, false),
(240005, 'Descuentos Percibidos', 'ganancia', 'IngrFina', false, true, false),
(240006, 'Alquileres Cobrados', 'ganancia', 'IngrFina', false, true, false),
(240007, 'Alquileres Ganados', 'ganancia', 'IngrFina', false, true, false),
(240008, 'Alquileres Producto', 'ganancia', 'IngrFina', false, true, false),
(240009, 'Alquileres Devengados', 'ganancia', 'IngrFina', false, true, false),
(240010, 'Alquileres Percibidos', 'ganancia', 'IngrFina', false, true, false),
(250001, 'Intereses Gastos', 'perdida', 'GastosFina', false, true, false),
(250002, 'Multas y Recargos', 'perdida', 'GastosFina', false, true, false),
(250003, 'Intereses Gasto', 'perdida', 'GastosFina', false, true, false),
(250004, 'Descuentos Concedidos', 'perdida', 'GastosFina', false, true, false),
(260001, 'Donativos', 'perdida', 'OtrosGtoFina', false, true, false),
(260002, 'Pérdida en Negociación de Activos', 'perdida', 'OtrosGtoFina', false, false, false),
(270001, 'Comisiones Percibidas', 'ganancia', 'Otring', false, true, false),
(270002, 'ISR sobre Rentas de Capital', 'ganancia', 'Otring', false, false, false),
(270003, 'Recuperación de Créditos', 'ganancia', 'Otring', false, true, false),
(270004, 'Regalías Percibidas', 'ganancia', 'Otring', false, true, false),
(270005, 'Sobrantes de Caja', 'ganancia', 'Otring', false, true, false),
(270006, 'Faltante de Caja', 'perdida', 'Otring', false, true, false),
(270007, 'Ganancia en Negociación de Activos', 'ganancia', 'Otring', false, false, false),
(270008, 'Ganancia en Venta de Activos', 'ganancia', 'Otring', false, true, false),
(270009, 'Dividendos Percibidos', 'ganancia', 'Otring', false, true, false),
(270010, 'Dividendos Ganados', 'ganancia', 'Otring', false, true, false),
(270011, 'Donativos Percibidos', 'ganancia', 'Otring', false, true, false),
(310100, 'Inventario Inicial de Materia Prima', 'costo_debe', 'MaterialesDirectos', true, true, true),
(310200, 'Compras de Materia Prima (Locales)', 'costo_debe', 'MaterialesDirectos', true, true, true),
(310300, 'Compras de Materia Prima (Importaciones)', 'costo_debe', 'MaterialesDirectos', true, true, true),
(310400, 'Impuestos Aduaneros / Aranceles', 'costo_debe', 'MaterialesDirectos', true, true, true),
(310500, 'Fletes y Seguros de Importación', 'costo_debe', 'MaterialesDirectos', true, true, true),
(310600, 'Gastos de Desaduanaje', 'costo_debe', 'MaterialesDirectos', true, true, true),
(310700, '(-) Devoluciones y Rebajas sobre Compras', 'costo_haber', 'MaterialesDirectos', true, true, true),
(310800, '(-) Inventario Final de Materia Prima', 'costo_haber', 'MaterialesDirectos', true, true, true),
(320100, 'Sueldos y Salarios', 'costo_debe', 'ManoObra', true, true, false),
(320200, 'Prestaciones Sociales y Cargas Patronales', 'costo_debe', 'ManoObra', true, true, false),
(320300, 'Horas Extra Directas', 'costo_debe', 'ManoObra', true, true, false),
(330100, 'Materiales Indirectos y Suministros', 'costo_debe', 'CostosIndirectos', true, true, false),
(330101, 'Envases en Departamento de Producción', 'costo_debe', 'CostosIndirectos', true, true, false),
(330200, 'Mano de Obra Indirecta (Supervisión)', 'costo_debe', 'CostosIndirectos', true, true, false),
(330300, 'Depreciaciones Maquinaria y Planta', 'costo_debe', 'CostosIndirectos', true, false, false),
(330400, 'Servicios Públicos de Fábrica', 'costo_debe', 'CostosIndirectos', true, true, false),
(330401, 'Fuerza Motriz', 'costo_debe', 'CostosIndirectos', true, true, false),
(330500, 'Alquileres y Seguros de Planta', 'costo_debe', 'CostosIndirectos', true, true, false),
(330501, 'Gastos de Instalación Fábrica', 'costo_debe', 'CostosIndirectos', true, true, false),
(330600, 'Bonificación Incentivo Fábrica', 'costo_debe', 'CostosIndirectos', true, true, false),
(330700, 'Reparación y Mantenimiento de Maquinaria', 'costo_debe', 'CostosIndirectos', true, true, true),
(330800, 'Depreciación Útiles y Enseres Fábrica', 'costo_debe', 'CostosIndirectos', true, false, false),
(330900, 'Grasas y Aceites Consumidos Fábrica', 'costo_debe', 'CostosIndirectos', true, true, true),
(331000, 'Amortización Gastos de Instalación Fábrica', 'costo_debe', 'CostosIndirectos', true, false, false),
(340101, 'Inventario Inicial Artículos en Proceso', 'costo_debe', 'CuentasInventarios', true, true, false),
(340102, 'Inventario Inicial Artículos Terminados', 'costo_debe', 'CuentasInventarios', true, true, false),
(340201, '(-) Inventario Final en Proceso', 'costo_haber', 'CuentasInventarios', true, true, false),
(340202, '(-) Inventario Final Artículos Terminados', 'costo_haber', 'CuentasInventarios', true, true, false);
